# Holds all information needed to run experiments.
excluded_measures:
  - GeometryScore
  - PWCCA
only_eval: True
experiments:
  - name: Vision Short Cut Correlation Experiments
    type: GroupSeparationExperiment # Defines the type of experiment class to use
    representation_dataset: "ColorDot_0_C100DataModule"
    filter_key_vals:  # Only keeps models that have any of the values for the keys.
      train_dataset:
        - ColorDot_100_C100DataModule
        - ColorDot_75_C100DataModule
        - ColorDot_0_C100DataModule
      architecture:
        - ViT_L32
        - ViT_B32
        - ResNet18
        - ResNet34
        - ResNet101  # ResNet 101 seed 0 is missing currently.
        - VGG11
        - VGG19
      seed:
        - 0
        - 1
        - 2
        - 3
        - 4
      domain: VISION
    grouping_keys: # Separates the trained models by this key into groups for the `GroupSeparationExperiment`.
      - train_dataset
    separation_keys: # Creates a separate experiment for each unique value of the key.
      - architecture
raw_results_filename: vision_shortcut_final.parquet # Must end with .parquet. The full results of all comparisons are stored in the results directory with this name

table_creation:
  save_full_df: True
  full_df_filename: vision_shortcut_final.csv
  # ---
  save_aggregated_df: True
  row_index: similarity_measure # The key to use as the row index in the table.
  columns: # The keys to use as columns (can be list[str] or a str)
    - identifier
    - representation_dataset
    - quality_measure
    - architecture
  value_key: value # The key specifying the value that fills the table (non-header/index values)
  filename: vision_shortcut_final.xlsx # Can be [.xlsx / .csv / .tex] file extension
