# Holds all information needed to run experiments.
threads: 1
cache_to_disk: false
cache_to_mem: true
only_extract_reps: false
rerun_nans: false
only_eval: false
experiments:
- name: NLP mnli Monotonicity Experiment (Using only CLS Token)
  type: MonotonicityExperiment   # Defines the type of experiment class to use
  representation_dataset: "mnli"
  filter_key_vals:   # Only keeps models that have any of the values for the keys.
    identifier:
    - Augmentation_0      # These models are set to only use the CLS token for representation comparison, but trained on the standard dataset
    train_dataset:
    - "mnli"
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    domain: NLP
    token_pos: 0
  grouping_keys:   # Separates the trained models by this key into groups for the `GroupSeparationExperiment`.
  - train_dataset
  separation_keys:   # Creates a separate experiment for each unique value of the key.
  - architecture
raw_results_filename: mono_nlp_standard_cls_tok_mnli.parquet # Must end with .parquet. The full results of all comparisons are stored in the results directory with this name

table_creation:
  save_full_df: true
  full_df_filename: mono_nlp_standard_mnli_bertAndAlbert_cls.csv
  # ---
  save_aggregated_df: true
  row_index: similarity_measure # The key to use as the row index in the table.
  columns: # The keys to use as columns (can be list[str] or a str)
  - quality_measure
  - architecture
  value_key: value # The key specifying the value that fills the table (non-header/index values)
  filename: mono_nlp_standard_cls_tok_mnli.csv # Can be [.xlsx / .csv / .tex] file extension
excluded_measures:
- GeometryScore
